// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/31/2024, 9:33:35 PM
const configMerger = require("D:/Bohdan/Projects/Freelance/astrodasha_ui/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["D:/Bohdan/Projects/Freelance/astrodasha_ui/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Bohdan/Projects/Freelance/astrodasha_ui/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Bohdan/Projects/Freelance/astrodasha_ui/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Bohdan/Projects/Freelance/astrodasha_ui/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Bohdan/Projects/Freelance/astrodasha_ui/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Bohdan/Projects/Freelance/astrodasha_ui/plugins/**/*.{js,ts,mjs}","D:/Bohdan/Projects/Freelance/astrodasha_ui/composables/**/*.{js,ts,mjs}","D:/Bohdan/Projects/Freelance/astrodasha_ui/utils/**/*.{js,ts,mjs}","D:/Bohdan/Projects/Freelance/astrodasha_ui/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/Bohdan/Projects/Freelance/astrodasha_ui/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/Bohdan/Projects/Freelance/astrodasha_ui/app.config.{js,ts,mjs}"] }));

module.exports = config
